"""Add referenced_sections to irs_bulletin_item

Revision ID: 0c6311150b0a
Revises: 44d2f0400188
Create Date: 2025-04-09 14:34:06.773428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6311150b0a'
down_revision: Union[str, None] = '44d2f0400188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irs_bulletin_item', sa.Column('referenced_sections', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irs_bulletin_item', 'referenced_sections')
    # ### end Alembic commands ###
