"""add form_field_statistics table

Revision ID: 0ccadec0375f
Revises: 9209160fa26a
Create Date: 2025-04-15 16:46:08.372754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ccadec0375f'
down_revision: Union[str, None] = '9209160fa26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_field_statistics',
    sa.Column('form_field_id', sa.Integer(), nullable=False),
    sa.Column('dollars', sa.Numeric(), nullable=True),
    sa.Column('forms', sa.Numeric(), nullable=True),
    sa.Column('people', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # Note: Foreign key constraints might need explicit naming for some DBs/conventions
    sa.ForeignKeyConstraint(['form_field_id'], ['form_fields.id'], name=op.f('fk_form_field_statistics_form_field_id_form_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_field_id', name=op.f('pk_form_field_statistics'))
    )
    # Removed incorrect alter_column and create_index operations on form_fields table
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_field_statistics')
    # Removed incorrect alter_column and drop_index operations on form_fields table
    # ### end Alembic commands ###
