"""add z score fields to us code sections

Revision ID: 351c04089af7
Revises: 0ccadec0375f
Create Date: 2024-08-15 17:01:35.472490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351c04089af7'
down_revision: Union[str, None] = '0ccadec0375f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - REMOVED UNWANTED CHANGES ###
    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_index('ix_form_fields_field_label', 'form_fields', ['field_label'], unique=False) # <-- REMOVED
    with op.batch_alter_table('us_code_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amendment_count_z', sa.Float(), nullable=True, comment='Z-score for amendment count relative to average.'))
        batch_op.add_column(sa.Column('bulletins_count_z', sa.Float(), nullable=True, comment='Z-score for IRS bulletin mentions relative to average.'))
        batch_op.add_column(sa.Column('section_count_z', sa.Float(), nullable=True, comment='Z-score for section text length relative to average.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - REMOVED UNWANTED CHANGES ###
    with op.batch_alter_table('us_code_section', schema=None) as batch_op:
        batch_op.drop_column('section_count_z')
        batch_op.drop_column('bulletins_count_z')
        batch_op.drop_column('amendment_count_z')

    # op.drop_index('ix_form_fields_field_label', table_name='form_fields') # <-- REMOVED
    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###
