"""Remove description from irs_bulletin_item

Revision ID: 41a7403a2925
Revises: 0c6311150b0a
Create Date: 2025-04-09 14:51:26.442142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a7403a2925'
down_revision: Union[str, None] = '0c6311150b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irs_bulletin_item', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irs_bulletin_item', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
