"""Remove page_start and page_end from irs_bulletin_item

Revision ID: 44d2f0400188
Revises: d2c1909e930a
Create Date: 2025-04-09 14:19:29.593758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d2f0400188'
down_revision: Union[str, None] = 'd2c1909e930a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irs_bulletin_item', 'page_start')
    op.drop_column('irs_bulletin_item', 'page_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irs_bulletin_item', sa.Column('page_end', sa.INTEGER(), nullable=True))
    op.add_column('irs_bulletin_item', sa.Column('page_start', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
