"""Add amendments_text and core_text columns to us_code_section

Revision ID: 6b6fbb6db86c
Revises: 2fd7b3c22451
Create Date: 2025-04-09 10:35:23.452781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6fbb6db86c'
down_revision: Union[str, None] = '2fd7b3c22451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_code_section', sa.Column('amendments_text', sa.Text(), nullable=True))
    op.add_column('us_code_section', sa.Column('core_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('us_code_section', 'core_text')
    op.drop_column('us_code_section', 'amendments_text')
    # ### end Alembic commands ###
