"""add section_complexity table

Revision ID: 6d75dd9f8f90
Revises: 351c04089af7
Create Date: 2024-08-15 17:34:26.603633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d75dd9f8f90'
down_revision: Union[str, None] = '351c04089af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED TO REMOVE form_fields CHANGES ###
    op.create_table('section_complexity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['us_code_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    with op.batch_alter_table('section_complexity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_complexity_section_id'), ['section_id'], unique=False) # Index is fine, even if unique=True on column

    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_index('ix_form_fields_field_label', 'form_fields', ['field_label'], unique=False) # <-- REMOVED
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED TO REMOVE form_fields CHANGES ###
    # op.drop_index('ix_form_fields_field_label', table_name='form_fields') # <-- REMOVED
    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    with op.batch_alter_table('section_complexity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_complexity_section_id'))

    op.drop_table('section_complexity')
    # ### end Alembic commands ###
