"""add section_impact table

Revision ID: 721ddd5d70a2
Revises: 98fc9945450a
Create Date: 2024-08-15 18:38:04.464491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721ddd5d70a2'
down_revision: Union[str, None] = '98fc9945450a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED TO REMOVE UNWANTED CHANGES ###
    op.create_table('section_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('revenue_impact', sa.Numeric(), nullable=True, comment='Estimated overall revenue impact (positive or negative). Units may vary.'),
    sa.Column('entity_impact', sa.Numeric(), nullable=True, comment='Estimated total number of entities (people, companies, etc.) significantly impacted.'),
    sa.Column('rationale', sa.Text(), nullable=True, comment='Explanation for the impact estimates.'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['us_code_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    with op.batch_alter_table('section_impact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_impact_section_id'), ['section_id'], unique=False)

    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_index('ix_form_fields_field_label', 'form_fields', ['field_label'], unique=False) # <-- REMOVED
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED TO REMOVE UNWANTED CHANGES ###
    # op.drop_index('ix_form_fields_field_label', table_name='form_fields') # <-- REMOVED
    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    with op.batch_alter_table('section_impact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_impact_section_id'))

    op.drop_table('section_impact')
    # ### end Alembic commands ###
