"""Remove relevance_notes from association table

Revision ID: 82753e3699de
Revises: 41a7403a2925
Create Date: 2025-04-09 15:12:52.809432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82753e3699de'
down_revision: Union[str, None] = '41a7403a2925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irs_bulletin_item_to_code_section', 'relevance_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irs_bulletin_item_to_code_section', sa.Column('relevance_notes', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
