"""add form_field_us_code_section_link table and relationships v2

Revision ID: 9209160fa26a
Revises: 378a4bbf05e9
Create Date: 2025-04-15 15:47:02.604027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9209160fa26a'
down_revision: Union[str, None] = '378a4bbf05e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_field_us_code_section_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_field_id', sa.Integer(), nullable=False),
    sa.Column('us_code_section_id', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['form_field_id'], ['form_fields.id'], name=op.f('fk_form_field_us_code_section_link_form_field_id_form_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['us_code_section_id'], ['us_code_section.id'], name=op.f('fk_form_field_us_code_section_link_us_code_section_id_us_code_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_field_us_code_section_link')),
    sa.UniqueConstraint('form_field_id', 'us_code_section_id', name='uq_form_field_section_link')
    )
    with op.batch_alter_table('form_field_us_code_section_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_field_us_code_section_link_form_field_id'), ['form_field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_field_us_code_section_link_us_code_section_id'), ['us_code_section_id'], unique=False)

    with op.batch_alter_table('us_code_section', schema=None) as batch_op:
        batch_op.alter_column('amendment_count',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('special_formatting',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('us_code_section', schema=None) as batch_op:
        batch_op.alter_column('special_formatting',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_nullable=True)
        batch_op.alter_column('amendment_count',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_nullable=True)

    with op.batch_alter_table('form_field_us_code_section_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_field_us_code_section_link_us_code_section_id'))
        batch_op.drop_index(batch_op.f('ix_form_field_us_code_section_link_form_field_id'))

    op.drop_table('form_field_us_code_section_link')
    # ### end Alembic commands ###
