"""add exemptions table

Revision ID: 98fc9945450a
Revises: 6d75dd9f8f90
Create Date: 2024-08-15 18:09:18.979433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fc9945450a'
down_revision: Union[str, None] = '6d75dd9f8f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED TO REMOVE UNWANTED CHANGES ###
    op.create_table('exemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('revenue_impact_estimate', sa.Numeric(), nullable=True, comment='Estimated revenue impact in thousands of dollars.'),
    sa.Column('entity_impact', sa.Numeric(), nullable=True, comment='Estimated total number of entities (people, companies, etc.) impacted.'),
    sa.Column('rationale', sa.Text(), nullable=True, comment='Explanation for why this is considered an exemption and its impact.'),
    sa.Column('relevant_text', sa.Text(), nullable=True, comment='Specific text snippet from the section identified as the exemption.'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['us_code_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exemptions_section_id'), ['section_id'], unique=False)

    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_index('ix_form_fields_field_label', 'form_fields', ['field_label'], unique=False) # <-- REMOVED
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - ADJUSTED TO REMOVE UNWANTED CHANGES ###
    # op.drop_index('ix_form_fields_field_label', table_name='form_fields') # <-- REMOVED
    # op.alter_column('form_fields', 'field_label', # <-- REMOVED
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    with op.batch_alter_table('exemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exemptions_section_id'))

    op.drop_table('exemptions')
    # ### end Alembic commands ###
